# HUB only: ServiceAccount used for tokens that spokes use to authenticate to the LokiStack gateway.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-log-writer
  namespace: openshift-logging
